import turtle
radius = eval(input("请输入半径"))
turtle.penup()
turtle.goto(-radius,0)
turtle.pendown()
turtle.circle(radius)
turtle.penup()
turtle.goto(radius,0)
turtle.pendown()
turtle.circle(radius)
turtle.penup()
turtle.goto(-radius,-2*radius)
turtle.pendown()
turtle.circle(radius)
turtle.penup()
turtle.goto(radius,-2*radius)
turtle.pendown()
turtle.circle(radius)
turtle.done()