import turtle
x , y = eval(input("请输入矩形中心坐标"))
a , b = eval(input("请输入长宽"))
turtle.penup()
turtle.goto(x - a / 2,y + b / 2)
turtle.pendown()
turtle.forward(a)
turtle.right(90)
turtle.forward(b)
turtle.right(90)
turtle.forward(a)
turtle.right(90)
turtle.forward(b)
turtle.done()